# Generated by Django 4.1.9 on 2023-05-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(error_messages={'unique': 'debe de ser unica'}, max_length=50, unique=True),
        ),
    ]
