# Generated by Django 4.1.9 on 2023-05-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_module'),
        ),
    ]
