# Generated by Django 4.1.9 on 2023-05-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_module_name_module_unique_module'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='module',
            name='unique_module',
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_module', violation_error_message='No es unica la clave del modulo'),
        ),
    ]
