# Generated by Django 4.1.9 on 2023-05-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_remove_module_unique_module_module_unique_module'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='module',
            name='unique_module',
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
