# Generated by Django 4.1.9 on 2023-07-15 05:48

from django.db import migrations
import my_utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_module_name_module_unique_name_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=my_utilities.fields.TrimpCharField(max_length=50),
        ),
    ]
