# Generated by Django 4.1.9 on 2023-07-15 05:42

from django.db import migrations
import menus.models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=menus.models.TrimpCharField(max_length=100),
        ),
    ]
