# Generated by Django 4.2.13 on 2024-05-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_menu_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="path",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
