# Generated by Django 4.2.13 on 2024-05-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_menu_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="depth",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
